name: pack

on: [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          - 1.17
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      # Cache go build cache, used to speedup go test
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            /go/pkg/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Mod download
        run: go mod download

      - run: |
          mkdir -p build

      - name: Build with xgo
        uses: TianTianBigWang/ghaction-xgo@master
        with:
          xgo_version: v0.1
          go_version: ${{ matrix.go_version }}
          pkg: cmd/ddshop
          dest: build
          prefix: ddshop
          targets: windows/amd64,linux/arm64,linux/amd64,darwin/arm64,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default

      - name: Move
        run: |
          ls ./build
          mkdir -p release
          mv $GITHUB_WORKSPACE/build/ddshop-darwin-10.16-amd64 release/ddshop_darwin_amd64 && chmod +x release/ddshop_darwin_amd64
          mv $GITHUB_WORKSPACE/build/ddshop-darwin-10.16-arm64 release/ddshop_darwin_arm64 && chmod +x release/ddshop_darwin_arm64
          mv $GITHUB_WORKSPACE/build/ddshop-linux-amd64 release/ddshop_linux_amd64 && chmod +x release/ddshop_linux_amd64
          mv $GITHUB_WORKSPACE/build/ddshop-windows-4.0-amd64.exe release/ddshop_windows_amd64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: result
          path: release
